base_url = "https://test-org-lior2.github.io"
title = "My Awesome Site"
description = "A simple Zola site"


build_search_index = true


# Enable syntax highlighting
[markdown]
highlight_code = true

    
